#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the isValid function below.
def isValid(s):
    y = set(s)
    l = []
    count = 0
    for x in y:
        l.append(s.count(x))
    for x in range(0,len(l)-1):
        if(l[x] != l[x+1]):
            if count == 0:
                if(l[x]>l[x+1]):
                    l[x] = l[x]-1
                else:
                    l[x+1] = l[x+1] - 1 
                count+=1    
                x-=1
            else:            
                return "NO"
    return "YES"        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = isValid(s)

    fptr.write(result + '\n')

    fptr.close()
