#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))
    count = [0] * 16    
    i = 0
    for x in range(0, 4):
        for y in range(0, 4):
            count[i] += (arr[x][y]+arr[x][y+1]+arr[x][y+2]+arr[x+1][y+1]+arr[x+2][y]+arr[x+2][y+1]+arr[x+2][y+2])
            i+=1    
        

    print("%d" %max(count))        
